-- Sample data for local development. Not applied to hosted projects.

insert into public.schools (name, street, town) values
  ('Newnham Croft Primary', 'Fen Causeway', 'Cambridge');

-- 2026/27 academic year default term dates. Inserted here, right after the
-- school, because on_default_term_created (see
-- 20260909123828_propagate_default_terms_to_schools.sql) fires on each of
-- these inserts and automatically creates the matching pair of half-term
-- terms rows (e.g. "Autumn 1 2026" / "Autumn 2 2026") for every existing
-- school — Newnham Croft Primary gets its terms this way, not from a
-- manual terms insert.
insert into public.default_terms (name, start_date, half_term_start, half_term_end, end_date) values
  ('Autumn 2026', '2026-09-01', '2026-10-27', '2026-10-31', '2026-12-22'),
  ('Spring 2027', '2027-01-05', '2027-02-16', '2027-02-20', '2027-03-27'),
  ('Summer 2027', '2027-04-13', '2027-05-25', '2027-05-29', '2027-07-20');

-- England & Wales bank holidays for the 2026/27 academic year, pulled from
-- gov.uk/bank-holidays.json on 2026-09-09 (see the "Refresh from gov.uk"
-- button, src/components/terms/actions.ts, for keeping these current —
-- this is just a starting point, not synced automatically).
insert into public.off_days (type, date, label) values
  ('bank_holiday', '2026-12-25', 'Christmas Day'),
  ('bank_holiday', '2026-12-28', 'Boxing Day'),
  ('bank_holiday', '2027-01-01', 'New Year''s Day'),
  ('bank_holiday', '2027-03-26', 'Good Friday'),
  ('bank_holiday', '2027-03-29', 'Easter Monday'),
  ('bank_holiday', '2027-05-03', 'Early May bank holiday'),
  ('bank_holiday', '2027-05-31', 'Spring bank holiday'),
  ('bank_holiday', '2027-08-30', 'Summer bank holiday');

insert into public.locations (school_id, name, address) values (
  (select id from public.schools where name = 'Newnham Croft Primary'),
  'Newnham Road crossing point',
  'Newnham Road, Cambridge'
);

insert into public.slots (location_id, day_of_week, start_time, end_time, label, capacity) values
  (
    (select id from public.locations where name = 'Newnham Road crossing point'),
    1, '08:15', '08:45', 'AM drop-off', 2
  ),
  (
    (select id from public.locations where name = 'Newnham Road crossing point'),
    1, '15:00', '15:30', 'PM pickup', 2
  );

-- Normally slot_instances are generated by publishing a term (Next.js, not
-- built yet) — hand-inserting a couple of dates here just for local data to
-- look at.
insert into public.slot_instances (slot_id, term_id, date, start_time, end_time, capacity, status) values
  (
    (select id from public.slots where label = 'AM drop-off'),
    (select id from public.terms where name = 'Autumn 1 2026'),
    '2026-09-07', '08:15', '08:45', 2, 'open'
  ),
  (
    (select id from public.slots where label = 'PM pickup'),
    (select id from public.terms where name = 'Autumn 1 2026'),
    '2026-09-07', '15:00', '15:30', 2, 'open'
  );

-- Login here is magic-link only (see src/app/login/actions.ts), which means
-- signing in re-uses the auth.users row instead of creating a fresh one —
-- GoTrue only recognizes that as "the same user" if the row looks like a
-- real confirmed signup (instance_id/aud/role/confirmed email) and has a
-- matching auth.identities row for the email provider. A bare
-- (id, email) insert is missing all of that, so signInWithOtp fails trying
-- to re-create a user that (from GoTrue's point of view) doesn't exist yet.
insert into auth.users (
  id, instance_id, aud, role, email,
  raw_app_meta_data, raw_user_meta_data,
  email_confirmed_at, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values
  (
    'a0000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000000',
    'authenticated', 'authenticated', 'vera.volunteer@example.com',
    '{"provider": "email", "providers": ["email"]}', '{}', now(), now(), now(),
    '', '', '', ''
  ),
  (
    'a0000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000000',
    'authenticated', 'authenticated', 'alex.admin@example.com',
    '{"provider": "email", "providers": ["email"]}', '{}', now(), now(), now(),
    '', '', '', ''
  );

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, created_at, updated_at, last_sign_in_at
) values
  (
    gen_random_uuid(), 'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000001', 'email',
    '{"sub": "a0000000-0000-0000-0000-000000000001", "email": "vera.volunteer@example.com"}',
    now(), now(), now()
  ),
  (
    gen_random_uuid(), 'a0000000-0000-0000-0000-000000000002',
    'a0000000-0000-0000-0000-000000000002', 'email',
    '{"sub": "a0000000-0000-0000-0000-000000000002", "email": "alex.admin@example.com"}',
    now(), now(), now()
  );

-- The on_auth_user_created trigger already created a volunteers row for
-- Vera (with display_name defaulted to her email prefix) the moment the
-- auth.users insert above ran — this just gives the seed data a nicer name,
-- same as a real user renaming themselves after signup.
update public.volunteers
set display_name = 'Vera'
where id = 'a0000000-0000-0000-0000-000000000001';

insert into public.school_admins (school_id, volunteer_id) values (
  (select id from public.schools where name = 'Newnham Croft Primary'),
  'a0000000-0000-0000-0000-000000000002'
);

-- Vera has to belong to a school before she can sign up for one of its
-- slots (see 20260801122733_add_volunteer_schools.sql).
insert into public.volunteer_schools (volunteer_id, school_id) values (
  'a0000000-0000-0000-0000-000000000001',
  (select id from public.schools where name = 'Newnham Croft Primary')
);

insert into public.signups (slot_instance_id, volunteer_id) values (
  (
    select id from public.slot_instances
    where date = '2026-09-07' and start_time = '08:15'
  ),
  'a0000000-0000-0000-0000-000000000001'
);

-- Role-named test accounts, one per privilege tier, for local login testing
-- (log in as superuser@example.com etc. via the magic-link flow instead of
-- signing up and manually flipping flags each time). Same full column set
-- as vera/alex above, for the same reason.
insert into auth.users (
  id, instance_id, aud, role, email,
  raw_app_meta_data, raw_user_meta_data,
  email_confirmed_at, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values
  (
    'a0000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000000',
    'authenticated', 'authenticated', 'superuser@example.com',
    '{"provider": "email", "providers": ["email"]}', '{}', now(), now(), now(),
    '', '', '', ''
  ),
  (
    'a0000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000000',
    'authenticated', 'authenticated', 'admin@example.com',
    '{"provider": "email", "providers": ["email"]}', '{}', now(), now(), now(),
    '', '', '', ''
  ),
  (
    'a0000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000000',
    'authenticated', 'authenticated', 'volunteer@example.com',
    '{"provider": "email", "providers": ["email"]}', '{}', now(), now(), now(),
    '', '', '', ''
  );

insert into auth.identities (
  id, user_id, provider_id, provider, identity_data, created_at, updated_at, last_sign_in_at
) values
  (
    gen_random_uuid(), 'a0000000-0000-0000-0000-000000000003',
    'a0000000-0000-0000-0000-000000000003', 'email',
    '{"sub": "a0000000-0000-0000-0000-000000000003", "email": "superuser@example.com"}',
    now(), now(), now()
  ),
  (
    gen_random_uuid(), 'a0000000-0000-0000-0000-000000000004',
    'a0000000-0000-0000-0000-000000000004', 'email',
    '{"sub": "a0000000-0000-0000-0000-000000000004", "email": "admin@example.com"}',
    now(), now(), now()
  ),
  (
    gen_random_uuid(), 'a0000000-0000-0000-0000-000000000005',
    'a0000000-0000-0000-0000-000000000005', 'email',
    '{"sub": "a0000000-0000-0000-0000-000000000005", "email": "volunteer@example.com"}',
    now(), now(), now()
  );

-- As above, on_auth_user_created already gave each of these a volunteers
-- row — this just grants the privileges their email implies.
update public.volunteers
set display_name = 'Superuser', is_superuser = true
where id = 'a0000000-0000-0000-0000-000000000003';

update public.volunteers
set display_name = 'Admin'
where id = 'a0000000-0000-0000-0000-000000000004';

update public.volunteers
set display_name = 'Volunteer'
where id = 'a0000000-0000-0000-0000-000000000005';

insert into public.volunteer_schools (volunteer_id, school_id) values (
  'a0000000-0000-0000-0000-000000000005',
  (select id from public.schools where name = 'Newnham Croft Primary')
);

insert into public.school_admins (school_id, volunteer_id) values (
  (select id from public.schools where name = 'Newnham Croft Primary'),
  'a0000000-0000-0000-0000-000000000004'
);
