-- Sample data for local development. Not applied to hosted projects.

insert into public.schools (name, address) values
  ('Newnham Croft Primary', 'Fen Causeway, Cambridge');

insert into public.locations (school_id, name, address) values (
  (select id from public.schools where name = 'Newnham Croft Primary'),
  'Newnham Road crossing point',
  'Newnham Road, Cambridge'
);

insert into public.slots (location_id, day_of_week, start_time, end_time, label, capacity) values
  (
    (select id from public.locations where name = 'Newnham Road crossing point'),
    1, '08:15', '08:45', 'AM drop-off', 2
  ),
  (
    (select id from public.locations where name = 'Newnham Road crossing point'),
    1, '15:00', '15:30', 'PM pickup', 2
  );

insert into public.terms (school_id, name, start_date, end_date, status) values (
  (select id from public.schools where name = 'Newnham Croft Primary'),
  'Autumn 1 2026', '2026-09-01', '2026-10-23', 'published'
);

-- Normally slot_instances are generated by publishing a term (Next.js, not
-- built yet) — hand-inserting a couple of dates here just for local data to
-- look at.
insert into public.slot_instances (slot_id, term_id, date, start_time, end_time, capacity, status) values
  (
    (select id from public.slots where label = 'AM drop-off'),
    (select id from public.terms where name = 'Autumn 1 2026'),
    '2026-09-07', '08:15', '08:45', 2, 'open'
  ),
  (
    (select id from public.slots where label = 'PM pickup'),
    (select id from public.terms where name = 'Autumn 1 2026'),
    '2026-09-07', '15:00', '15:30', 2, 'open'
  );

insert into auth.users (id, email) values
  ('a0000000-0000-0000-0000-000000000001', 'vera.volunteer@example.com'),
  ('a0000000-0000-0000-0000-000000000002', 'alex.admin@example.com');

insert into public.volunteers (id, display_name) values
  ('a0000000-0000-0000-0000-000000000001', 'Vera');

insert into public.school_admins (school_id, user_id) values (
  (select id from public.schools where name = 'Newnham Croft Primary'),
  'a0000000-0000-0000-0000-000000000002'
);

insert into public.signups (slot_instance_id, volunteer_id) values (
  (
    select id from public.slot_instances
    where date = '2026-09-07' and start_time = '08:15'
  ),
  'a0000000-0000-0000-0000-000000000001'
);
