-- Dates a term's slot_instances should be excluded/cancelled for when
-- generated by publishing a term. Two kinds, sharing one table since
-- they're the same shape (a date to exclude, optionally labelled) and
-- differ only in scope:
--   - bank_holiday: applies to every school (school_id null)
--   - inset_day: a specific school's own staff-training day (school_id set)
-- Explicit `type` rather than relying on school_id's nullness alone to
-- convey which - makes the distinction self-documenting, and the check
-- constraint below turns "bank holidays are global, inset days aren't"
-- from a convention into an enforced invariant.
create table public.off_days (
  id bigint generated always as identity primary key,
  type text not null check (type in ('bank_holiday', 'inset_day')),
  school_id bigint references public.schools (id),
  date date not null,
  label text,
  created_at timestamptz not null default now(),
  check (
    (type = 'bank_holiday' and school_id is null) or
    (type = 'inset_day' and school_id is not null)
  )
);

alter table public.off_days enable row level security;

-- Same visibility rationale as default_terms: internal admin-tooling input
-- to term publishing, not public-facing itself (the public sees the
-- resulting cancelled slot_instances once a term is published, not this
-- table directly) - scoped to signed-in users, not anon.
grant select, insert, update, delete on public.off_days to authenticated, service_role;

create policy "signed-in users can view off days"
on public.off_days
for select
to authenticated
using (true);

-- is_school_admin(null) is always false (no school_admins row can match a
-- null school_id), so this naturally restricts bank_holiday rows
-- (school_id null) to superusers only, while letting a school's own admin
-- manage that school's inset_day rows - same is_school_admin(...) or
-- is_superuser() pattern already used for terms/locations/slots.
create policy "school admins and superusers manage off days"
on public.off_days
for all
to authenticated
using (is_superuser() or is_school_admin(school_id))
with check (is_superuser() or is_school_admin(school_id));
